serverAddr = "0.0.0.0"
serverPort = 7000

# 使用token鉴权
auth.method = "token"
auth.token = "your_token"

# 转发ssh
# [[proxies]] 
# name = "ssh"
# type = "tcp"
# localIP = "127.0.0.1"
# localPort = 22
# remotePort = 2222